### ISSUE TITLE
Crazy layout

### ISSUE THREAD

**Issue by eugbrh** [just-harry/tiny-ui-fix-for-ts3#3]
Hey! I really love the idea of this mod, I've been waiting for something like this for years. Unfortunatelly, I haven't got a chanse to try it out because of the bug that caused everything to go mess. I use Windows 11 with 1.69 version of the game.

<img width="1282" alt="Screenshot 2023-12-29 173412" src="https://github.com/just-harry/tiny-ui-fix-for-ts3/assets/152988954/dd43f3c0-9d3b-49bc-96d0-05f4cafeaf8c">
<img width="1282" alt="Screenshot 2023-12-29 173449" src="https://github.com/just-harry/tiny-ui-fix-for-ts3/assets/152988954/47e3c2d9-6b84-4426-83b6-d3bfae14e4c3">

**Comment by just-harry** [comment]
Hmm, that's strange: may I ask which version of the script you're using? (it should be printed after the script starts up). \
And, if you're using any mods?

**Comment by eugbrh** [comment]
I'm using the latest version of the script (1.0.5) and there's a bunch of mods installed
By the way, I'm using the smooth patch and some graphics mods, maybe those are the problem

**Comment by just-harry** [comment]
I've just released version 1.1.0 of the script, which has improved handling of `Resource.cfg` files.
That might fix your issue.

If not: when the script runs it'll print a bunch of messages starting with "Scaling the resources of the package at", could you copy those messages into a reply in this issue, please, so that I can try to inspect their corresponding mods for conflicts?

**Comment by eugbrh** [comment]
I guess the problem is still the same. Here are the messages:

Scaling the resources of the package at "D:\Games\The Sims 3\Game\Bin\UI\UI.package".
Scaling the resources of the package at "D:\Games\The Sims 3\GameData\Shared\Packages\DeltaBuild0.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\LD\ld_AutoLightsOverhaul.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\LD\ld_Common.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\LD\ld_RandomSimFixes.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\LD\ld_SetHourCheat.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\ani_FridgeMod.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_ErrorTrap.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_MasterController.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_MasterControllerCheats.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_Mover.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_NoCD.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_Overwatch.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_Register.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_Relativity.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_StoryProgression.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_Tagger.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Nraas\NRaas_Tempest.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Patch\ld_SmoothPatch.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\Patch\ld_SmoothPatch_MasterController.package".
Scaling the resources of the package at "C:\Users\edb\Documents\Electronic Arts\The Sims 3\Mods\Packages\[Sleepy-Genius]TaxiCharge.package".
Scaling the resources of the package at "D:\Games\The Sims 3\GameData\Shared\Packages\ContentPatch.package".
Scaling the resources of the package at "D:\Games\The Sims 3\Game\Bin\gameplay.package".
Scaling the resources of the package at "D:\Games\The Sims 3\Game\Bin\scripts.package".
Scaling the resources of the package at "D:\Games\The Sims 3\Game\Bin\simcore.package".
Scaled 654 layouts, and 7 CSS text-styles.

**Comment by just-harry** [comment]
Thank you for providing that list, I had some time to look at this evening, and I ruled out mod incompatibility being the cause of this.
Instead, I think this was caused by the system locale not using dots for decimal-points.

This should be fixed in version 1.3.0, which I've just released.

**Comment by just-harry** [comment]
I'm pretty sure that version 1.3.0 fixed this, so I'm going to go ahead and close this issue.
Please feel free to reopen this issue if hasn't actually been fixed.
